### ISSUE TITLE
用Chrome指纹报错

### ISSUE THREAD

**Issue by mygit-2023** [LyleMi/ja3proxy#1]
➜ ./ja3proxy -port 8080 -client Chrome -version 106                             
HTTP Proxy Server started at localhost Port:8080
2023/07/15 15:45:09 proxy to kawayiyi.com:443
2023/07/15 15:45:10 copy dest to client error read tcp 127.0.0.1:8080->127.0.0.1:56461: use of closed network connection

$ curl -v  -k --proxy http://localhost:8080 https://kawayiyi.com/tls
*   Trying 127.0.0.1:8080...
* Connected to localhost (127.0.0.1) port 8080 (#0)
* CONNECT tunnel: HTTP/1.1 negotiated
* allocate connect buffer
* Establish HTTP proxy tunnel to kawayiyi.com:443
> CONNECT kawayiyi.com:443 HTTP/1.1
> Host: kawayiyi.com:443
> User-Agent: curl/8.1.2
> Proxy-Connection: Keep-Alive
>
< HTTP/1.1 200 OK
< Date: Sat, 15 Jul 2023 07:50:40 GMT
< Transfer-Encoding: chunked
* Ignoring Transfer-Encoding in CONNECT 200 response
<
* CONNECT phase completed
* CONNECT tunnel established, response 200
* schannel: disabled automatic use of client certificate
* using HTTP/1.x
> GET /tls HTTP/1.1
> Host: kawayiyi.com
> User-Agent: curl/8.1.2
> Accept: */*
>
* Received HTTP/0.9 when not allowed
* Closing connection 0
* schannel: shutting down SSL/TLS connection with kawayiyi.com port 443
curl: (1) Received HTTP/0.9 when not allowed

**Comment by LyleMi** [comment]
This is due to the fact that the fingerprint of Chrome version 106 actively requests the server to use HTTP/2, whereas curl does not use HTTP/2, resulting in this issue. Using the following command should resolve your issue:

```bash
curl -v -k --proxy http://localhost:8080/ https://kawayiyi.com/tls --http2
```

Thank you for your feedback, I will include it in the README.
