### ISSUE TITLE
How can I solve the problem that the certificate is not secure when using it

### ISSUE THREAD

**Issue by xiaoweigege** [LyleMi/ja3proxy#3]
How can I solve the problem that the certificate is not secure when using it

**Comment by LyleMi** [comment]
There are several ways to solve this problem. Firstly, the program can generate certificates automatically during runtime, and you can import the corresponding certificate into the operating system. Secondly, you can address the issue by configuring the security mode of your browser or command-line tool, such as setting a flag in Chrome to ignore certificate errors. Lastly, you can set a valid certificate during program startup.

**Comment by xiaoweigege** [comment]
I have imported the generated certificate into the system, but it still shows a security error, and I wish I could do what charles did and not report a security error
