### ISSUE TITLE
Certificate generation does not respect CLI arguments

### ISSUE THREAD

**Issue by rosahaj** [LyleMi/ja3proxy#5]
# Problem

When `-cert` and `-key` flags are provided but those files don't exist, ja3proxy creates the certificate and key at the default locations but still attempts to use the paths provided by the flags. This issue also occurs when using the `compose.yaml` provided in #4. 

## Walkthrough
1. Cert or key isn't found, calls `generateCertificate()`
https://github.com/LyleMi/ja3proxy/blob/a485d3702d942a54f7b916bc578839050e8541fe/proxy.go#L162-L165

2. Cert generation uses default path:
https://github.com/LyleMi/ja3proxy/blob/a485d3702d942a54f7b916bc578839050e8541fe/cert.go#L38

3. Key generation uses default path:
https://github.com/LyleMi/ja3proxy/blob/a485d3702d942a54f7b916bc578839050e8541fe/cert.go#L45

4. Proxy unsuccessfully attempts to find cert and key at specified paths and fails:
https://github.com/LyleMi/ja3proxy/blob/a485d3702d942a54f7b916bc578839050e8541fe/proxy.go#L89-L92

# Proposed solution

Create cert and key at the paths specified through the CLI, by passing `Config.Cert` and `Config.Key` to the `generateCertificate` function. Throw an error if only one those files exists (do not overwrite either one).

Unless I'm overlooking something, I believe it would also make more sense to load the certificates on proxy startup (inside `main()`) and not on every connection:
https://github.com/LyleMi/ja3proxy/blob/a485d3702d942a54f7b916bc578839050e8541fe/proxy.go#L89

**Comment by LyleMi** [comment]
Thank you for taking the time to bring these two new requirements to my attention. I appreciate your feedback and will do my best to address them as soon as possible. However, due to my busy work schedule, I may not be able to fulfill these requirements immediately. Nevertheless, I will try my best to allocate some time in the near future to work on them.

Thank you for your patience and understanding.

Best regards,
Lyle

**Comment by rosahaj** [comment]
> Thank you for taking the time to bring these two new requirements to my attention. I appreciate your feedback and will do my best to address them as soon as possible. However, due to my busy work schedule, I may not be able to fulfill these requirements immediately. Nevertheless, I will try my best to allocate some time in the near future to work on them.
> 
> Thank you for your patience and understanding.
> 
> Best regards, Lyle

I had the time to write a short PR to fix the certificate generation issue (#6). I confirmed that it works with both the native binary and docker. Feel free to look at it whenever your schedule allows for it.

I will separate the certificate loading improvement into a new issue so this one can be closed.
